name: test-sql-files

on:
  workflow_call:

jobs:
  test-sql-files:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Install postgres
        run: "sudo apt-get install -y postgresql"
      - name: Copy sql files to tmp directory and test applying them
        run: |
          #!/bin/bash
          set -ex
          sudo systemctl start postgresql.service
          ./postgres/scripts/bootstrap-db.sh local
